image: "flowdalic/debian-dev:1.6"

before_script:
  - apt update

build:
  script:
    - python3 ./setup.py build

test:
  script:
    - |
      cd tests
      touch cweb-latex/disable
      touch graphicx-dotted-files/disable
      touch pythontex/disable
      ./run.sh --debchroot *
