image: "flowdalic/debian-dev:1.6"

before_script:
  - apt update

build:
  script:
    - apt-get install -y texinfo
    - make build

test:
  script:
    - |
      cd tests
      touch cweb-latex/disable
      touch graphicx-dotted-files/disable
      touch pythontex/disable
      ./run.sh --debchroot *

lint:
  script: make lint
